import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service - Rizzer',
  description: 'Terms of Service for Rizzer - Your AI Dating Coach',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="bg-gradient-to-r from-rizzer-pink to-rizzer-salmon text-white py-6">
        <div className="container-custom">
          <Link href="/" className="text-2xl font-bold hover:opacity-80 transition-opacity">
            ← Back to Rizzer
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="container-custom py-16 max-w-4xl">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">Terms of Service</h1>
        <p className="text-gray-600 mb-8">Last updated: November 7, 2025</p>

        <div className="prose prose-lg max-w-none space-y-8">
          <section>
            <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing or using Rizzer ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the App. We reserve the right to modify these Terms at any time, and your continued use of the App constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">2. Description of Service</h2>
            <p className="text-gray-700 leading-relaxed">
              Rizzer is an AI-powered dating coach application that provides personalized conversation starters, date ideas, gift recommendations, and relationship advice. The App uses artificial intelligence to analyze your inputs and provide customized suggestions to enhance your dating experience.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">3. User Eligibility</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              To use Rizzer, you must:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Be at least 18 years of age</li>
              <li>Have the legal capacity to enter into these Terms</li>
              <li>Not be prohibited from using the App under applicable laws</li>
              <li>Provide accurate and complete registration information</li>
              <li>Maintain the security of your account credentials</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">4. User Accounts</h2>
            <p className="text-gray-700 leading-relaxed">
              You are responsible for maintaining the confidentiality of your account and password. You agree to accept responsibility for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account or any other breach of security.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">5. Acceptable Use</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              You agree not to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Use the App for any illegal or unauthorized purpose</li>
              <li>Violate any laws in your jurisdiction</li>
              <li>Infringe upon the rights of others</li>
              <li>Transmit any harmful code or malware</li>
              <li>Attempt to gain unauthorized access to the App or its systems</li>
              <li>Use the App to harass, abuse, or harm another person</li>
              <li>Impersonate any person or entity</li>
              <li>Collect or store personal data about other users</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">6. AI-Generated Content</h2>
            <p className="text-gray-700 leading-relaxed">
              The advice, suggestions, and content generated by Rizzer's AI are for informational and entertainment purposes only. We do not guarantee the accuracy, completeness, or usefulness of any AI-generated content. You are solely responsible for how you use the suggestions provided by the App.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">7. Subscription and Payments</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              Rizzer may offer subscription plans with various features. By subscribing, you agree to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-700">
              <li>Pay all applicable fees as described in the App</li>
              <li>Automatic renewal unless cancelled before the renewal date</li>
              <li>Our refund policy as stated in the App</li>
              <li>Price changes with advance notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">8. Intellectual Property</h2>
            <p className="text-gray-700 leading-relaxed">
              All content, features, and functionality of the App, including but not limited to text, graphics, logos, icons, images, and software, are the exclusive property of Rizzer and are protected by copyright, trademark, and other intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">9. User Content</h2>
            <p className="text-gray-700 leading-relaxed">
              You retain ownership of any content you submit to the App. By submitting content, you grant Rizzer a worldwide, non-exclusive, royalty-free license to use, reproduce, and process your content solely for the purpose of providing and improving our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">10. Disclaimer of Warranties</h2>
            <p className="text-gray-700 leading-relaxed">
              THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">11. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, RIZZER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">12. Termination</h2>
            <p className="text-gray-700 leading-relaxed">
              We may terminate or suspend your account and access to the App immediately, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the App will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">13. Governing Law</h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">14. Contact Information</h2>
            <p className="text-gray-700 leading-relaxed">
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="text-gray-700 leading-relaxed mt-4">
              Email: support@rizzer.app<br />
              Address: [Your Business Address]
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-8 mt-16">
        <div className="container-custom text-center">
          <p className="text-gray-400">
            © 2025 Rizzer. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
